### PR TITLE
If .rbenv-vars isn't present but .env is, use that.

### PR DESCRIPTION
**Pull request by andyjeffries**
Allows you to use the same file as Foreman (https://github.com/ddollar/foreman), a commonly used tool for developers targeting Heroku (as well as any other environment variable based deployment).

### CODE REVIEW

**Comment by jasonkarns** [comment]
This is old, but I wanted to comment on the (now somewhat prevalent) [dotenv](https://github.com/bkeepers/dotenv)

This particular project is a gem for ruby/rails, but expects a standard source-able file with `key=value` pairs and optional `export` commands.

There is also a node variant based on the same file format: [dotenv](https://github.com/motdotla/dotenv)

**Comment by mislav** [comment]
I'm :+1: for supporting `.env` files if it's done in a manner compatible with other solutions which source `.env` files.

**Comment by sstephenson** [comment]
:-1: on supporting `.env` files. IMO, rbenv-vars is finished, feature-wise. I don’t see any reason to add support for a different file format here—let’s make a new plugin instead.

**Comment by andyjeffries** [comment]
I disagree with you @sstephenson.

`.rbenv-vars` is a superset of `.env`, so why not try to read `.rbenv-vars` and then `.env`, then  using the same parsing code.  It means that it just works with already existing `.env` files rather than having to symlink them.  

The patch is very small, so it's an additional feature for next-to-no-impact.  

Making another plugin (effectively a complete fork of this project, strip out some of the features, make it look for `.env` and then be sure to track changes to the upstream project feels like a complete waste of effort in terms of duplication)

**Comment by mislav** [comment]
@andyjeffries Well, since this is @sstephenson's project and he seems pretty adamant about not adding new features to it, I guess there's little point in arguing.

The patch is small, but potential ramifications (and future maintenance) could be significant. I agree that the best approach might be to create a new plugin that only handles `.env` files. Then, for people who need both, they can install both plugins.

**Comment by andyjeffries** [comment]
Fair enough.

**Pull request closed without merging**
